name: flutter_cubit_search_app
description: "A new Flutter project."
publish_to: 'none' # 
version: 1.0.0+1

environment:
  # Mimimum Dart SDK sürümü
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  # Localization (L10N)
  flutter_localizations:
    sdk: flutter
  # Cupertino stili iOS ikonları
  cupertino_icons: ^1.0.8
  # Routing & Navigation
  go_router: ^14.3.0
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

dev_dependencies:
  # Test
  flutter_test:
    sdk: flutter
  # Linting & Code Quality
  flutter_lints: ^4.0.0

# Flutter yapılandırma ayarları
flutter:
  # Material Design bileşenlerini kullan
  uses-material-design: true

  # Otomatik dosya üretimini etkinleştir
  generate: true 

  